/**
 * Kenyan reference data for onboarding forms.
 *
 * All 47 counties created under the 2010 Constitution, alphabetical so a
 * merchant can scan straight to theirs.
 */
export const COUNTIES = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita - Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
] as const;

/** Commercial banks licensed by the Central Bank of Kenya, alphabetical. */
export const BANKS = [
  "ABC Bank",
  "Absa Bank Kenya",
  "Access Bank Kenya",
  "Bank of Africa Kenya",
  "Bank of Baroda",
  "Bank of India",
  "Citibank Kenya",
  "Consolidated Bank of Kenya",
  "Co-operative Bank of Kenya",
  "Credit Bank",
  "Diamond Trust Bank (DTB)",
  "DIB Bank Kenya",
  "Ecobank Kenya",
  "Equity Bank Kenya",
  "Family Bank",
  "Faulu Microfinance Bank",
  "Guaranty Trust Bank (GTBank)",
  "Guardian Bank",
  "Gulf African Bank",
  "Habib Bank AG Zurich",
  "HF Group (Housing Finance)",
  "I&M Bank",
  "KCB Bank Kenya",
  "Kingdom Bank",
  "Mayfair CIB Bank",
  "Middle East Bank Kenya",
  "M Oriental Bank",
  "National Bank of Kenya",
  "NCBA Bank Kenya",
  "Paramount Bank",
  "Premier Bank Kenya",
  "Prime Bank",
  "SBM Bank Kenya",
  "Sidian Bank",
  "Stanbic Bank Kenya",
  "Standard Chartered Bank Kenya",
  "UBA Kenya Bank",
  "Victoria Commercial Bank",
] as const;
