import type { CSSProperties } from "react";

/**
 * Onboarding wizard styles, taken from the design bundle's rendered DOM
 * ("03 Merchant Onboarding.html", inspected via getComputedStyle - see
 * CLAUDE.md's "Getting the real screen source" philosophy, same approach
 * applied to this static bundle rather than the live design canvas) and
 * cross-checked against `packages/ui/src/tokens.ts`. Kept as literal
 * values rather than Tailwind utilities, same reasoning as
 * `apps/merchant/src/components/auth/styles.ts`.
 */
export const O = {
  page: {
    minHeight: "100vh",
    background: "#FAFBFC",
    fontFamily: "'Instrument Sans',sans-serif",
    color: "#1A1F2B",
    display: "flex",
    flexDirection: "column",
    minWidth: 360,
  },

  // --- top bar ----------------------------------------------------------
  topBar: {
    background: "#FFFFFF",
    borderBottom: "1px solid #E4E7EC",
    padding: "13px clamp(18px,4vw,40px)",
  },
  topBarInner: {
    maxWidth: 1120,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  },
  logo: { height: "clamp(32px,7vw,42px)", width: "auto", display: "block" },
  topBarRight: { display: "flex", alignItems: "center", gap: 13 },
  saveState: { font: "500 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".08em" },
  saveStateSaved: { color: "#0B8A5B" },
  saveStateUnsaved: { color: "#A7AEBB" },
  topBarRule: { width: 1, height: 14, background: "#E4E7EC" },
  onboardingLabel: {
    font: "500 11px/1 'IBM Plex Mono',monospace",
    letterSpacing: ".08em",
    color: "#838C9B",
  },
  // Understated on purpose - this isn't in the design canvas's onboarding
  // screen, so it's kept to the top bar's existing mono/letter-spaced
  // idiom rather than introducing a new visual weight.
  logoutButton: {
    font: "500 11px/1 'IBM Plex Mono',monospace",
    letterSpacing: ".08em",
    color: "#838C9B",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
  },
  // Three rule sizes, per surface - topbar 24×6, section eyebrow 22×5,
  // inside the dark card 20×5.
  skewRule: { display: "block", width: 22, height: 5, background: "#D81E32", transform: "skewX(-14deg)", flex: "0 0 auto" },
  skewRuleTopBar: { display: "block", width: 24, height: 6, background: "#D81E32", transform: "skewX(-14deg)" },
  skewRuleDark: { display: "block", width: 20, height: 5, background: "#D81E32", transform: "skewX(-14deg)", flex: "0 0 auto" },

  // --- stepper ------------------------------------------------------------
  stepperBar: { background: "#FFFFFF", borderBottom: "1px solid #E4E7EC", padding: "0 clamp(18px,4vw,40px)" },
  stepperInner: {
    maxWidth: 1120,
    margin: "0 auto",
    display: "flex",
    alignItems: "stretch",
    overflow: "auto",
  },
  // The active underline is an inset shadow on the item itself, not a
  // separate absolutely-positioned bar.
  stepItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "15px 18px",
    flex: "0 0 auto",
    background: "none",
    border: "none",
    borderRadius: 0,
    font: "inherit",
    textAlign: "left",
  } as CSSProperties,
  stepCircle: {
    width: 25,
    height: 25,
    borderRadius: 999,
    font: "600 12px/23px 'IBM Plex Mono',monospace",
    textAlign: "center",
    flex: "0 0 auto",
  } as CSSProperties,
  stepLabel: { font: "600 13px/1.3 'Instrument Sans',sans-serif", whiteSpace: "nowrap" } as CSSProperties,

  // --- shell / content ----------------------------------------------------
  content: { flex: "1 1 0%", padding: "clamp(26px,5vw,48px) clamp(18px,4vw,40px) clamp(40px,7vw,72px)" },
  contentInner: { maxWidth: 1120, margin: "0 auto" },
  /**
   * Each step sits in its own left-aligned column inside the 1120 shell -
   * the widths differ per screen in the design and are *not* centred, so
   * every heading shares the same left edge as the stepper above it.
   */
  wDetails: { maxWidth: 840 },
  wFleet: { maxWidth: 960 },
  wVehicleForm: { maxWidth: 1080 },
  wDocuments: { maxWidth: 900 },
  wReview: { maxWidth: 1020 },

  // --- vehicle form: wide form column + sticky earnings aside -------------
  formRow: { display: "flex", gap: 16, alignItems: "flex-start" },
  formMain: { flex: "3 1 430px", minWidth: 0 },
  formCard: {
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 12,
    padding: "clamp(18px,3vw,28px)",
  },
  formFields: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 18 },

  earnAside: {
    flex: "1 1 250px",
    minWidth: 0,
    position: "sticky",
    top: 16,
    border: "1px solid #DCE1FA",
    borderRadius: 12,
    overflow: "hidden",
    background: "#EDEFFC",
  } as CSSProperties,
  earnHead: { display: "flex", alignItems: "center", gap: 10, padding: "13px 16px", background: "#FFFFFF" },
  earnHeadText: { font: "500 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".1em", color: "#5A6373" },
  earnRule: { display: "block", width: 18, height: 5, background: "#D81E32", transform: "skewX(-14deg)", flex: "0 0 auto" },
  earnRow: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
    padding: "11px 16px",
    borderTop: "1px solid #DCE1FA",
  },
  earnLabel: { minWidth: 0, font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#333B4A" },
  earnSub: { display: "block", color: "#838C9B", marginTop: 3 },
  earnValue: {
    font: "600 12px/1.3 'IBM Plex Mono',monospace",
    fontVariant: "tabular-nums",
    color: "#0B0F1A",
    textAlign: "right",
    flex: "0 0 auto",
  } as CSSProperties,
  earnHighlight: { padding: "14px 16px", background: "#DCE1FA", borderTop: "1px solid #B6C0F4" },
  earnHighlightLabel: { font: "600 12px/1.35 'Instrument Sans',sans-serif", color: "#0B0F1A", marginBottom: 6 },
  earnHighlightValue: {
    font: "700 26px/1 Archivo,sans-serif",
    fontVariant: "tabular-nums",
    color: "#0B0F1A",
  } as CSSProperties,
  earnHighlightKes: { font: "500 11px/1 'Instrument Sans',sans-serif", color: "#5A6373", marginRight: 6 },
  earnNote: {
    padding: "12px 16px",
    background: "#FFFFFF",
    borderTop: "1px solid #DCE1FA",
    font: "400 12px/1.5 'Instrument Sans',sans-serif",
    color: "#5A6373",
    textWrap: "pretty",
  } as CSSProperties,
  twoCol: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(320px,1fr))",
    gap: "clamp(26px,4vw,48px)",
    alignItems: "start",
  },
  backLink: {
    font: "600 13px/1 'Instrument Sans',sans-serif",
    color: "#5A6373",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    marginBottom: 16,
  },
  /**
   * The "Back" in a step's bottom action row, opposite a primary button -
   * a real button with its own hit area, not a bare link flush to the
   * page edge. Different from `backLink` above, which is the small
   * breadcrumb before a screen's heading (e.g. "All vehicles").
   */
  backLinkRow: {
    height: 44,
    padding: "0 18px",
    background: "transparent",
    color: "#5A6373",
    border: "1px solid transparent",
    borderRadius: 8,
    font: "600 14px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
    transition: "background 120ms cubic-bezier(.2,.8,.25,1), color 120ms cubic-bezier(.2,.8,.25,1)",
  } as CSSProperties,
  // Ghost-button hover per the design system's button spec - same as the
  // rule this repo already follows for primary/secondary/danger hover.
  backLinkRowHover: { background: "#F1F3F6", color: "#0B0F1A" },

  eyebrow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 18 },
  eyebrowText: { font: "500 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".13em", color: "#838C9B" },
  stepEyebrow: { font: "500 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".11em", color: "#9AA2B0", marginBottom: 10 },

  h1Display: {
    margin: "0 0 16px",
    font: "700 clamp(32px,5.2vw,46px)/1.02 Archivo,sans-serif",
    fontVariationSettings: "'wdth' 110",
    letterSpacing: "-.03em",
    color: "#0B0F1A",
    textWrap: "balance",
  } as CSSProperties,
  h1Step: {
    margin: "0 0 9px",
    font: "600 clamp(25px,3.6vw,32px)/1.12 Archivo,sans-serif",
    fontVariationSettings: "'wdth' 106",
    letterSpacing: "-.022em",
    color: "#0B0F1A",
  } as CSSProperties,
  lede: {
    margin: "0 0 20px",
    font: "400 16px/1.6 'Instrument Sans',sans-serif",
    color: "#5A6373",
    maxWidth: 520,
    textWrap: "pretty",
  } as CSSProperties,

  stepLede: {
    margin: 0,
    font: "400 15px/1.6 'Instrument Sans',sans-serif",
    color: "#5A6373",
    maxWidth: 560,
    textWrap: "pretty",
  } as CSSProperties,

  pillRow: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 24 },
  pill: {
    padding: "6px 12px",
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 999,
    font: "600 12px/1.2 'Instrument Sans',sans-serif",
    color: "#333B4A",
  },
  // The "Have these ready" chips are a lighter, tinted variant of the pill.
  docPill: {
    padding: "5px 11px",
    background: "#F8F9FB",
    border: "1px solid #E4E7EC",
    borderRadius: 999,
    font: "500 12px/1.3 'Instrument Sans',sans-serif",
    color: "#333B4A",
  },
  docPillRow: { display: "flex", gap: 7, flexWrap: "wrap" },

  // --- numbered step cards (welcome screen) --------------------------------
  numberedList: { display: "grid", gap: 10, marginBottom: 26 },
  numberedCard: {
    display: "flex",
    gap: 13,
    alignItems: "flex-start",
    padding: "14px 16px",
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 12,
  },
  numberedDigit: {
    width: 24,
    height: 24,
    borderRadius: 999,
    background: "#EDEFFC",
    color: "#0F23A8",
    font: "600 12px/24px 'IBM Plex Mono',monospace",
    textAlign: "center",
    flex: "0 0 auto",
  } as CSSProperties,
  numberedTitle: { font: "600 14px/1.3 'Instrument Sans',sans-serif", color: "#0B0F1A", marginBottom: 3 },
  numberedBody: { font: "400 13px/1.5 'Instrument Sans',sans-serif", color: "#5A6373" },

  actionsRow: { display: "flex", gap: 11, flexWrap: "wrap", alignItems: "center" },

  // --- dark earnings card ---------------------------------------------------
  rightCol: { display: "grid", gap: 14 },
  darkCard: {
    background: "#0B0F1A",
    borderRadius: 12,
    padding: 22,
  },
  darkEyebrow: { display: "flex", alignItems: "center", gap: 11, marginBottom: 15 },
  darkEyebrowText: { font: "500 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".1em", color: "#8C97A8" },
  kesBig: { display: "flex", alignItems: "baseline", gap: 10, marginBottom: 8, flexWrap: "wrap" },
  kesPrefix: { font: "500 14px/1 'Instrument Sans',sans-serif", color: "#8C97A8", letterSpacing: ".04em" },
  kesValue: {
    font: "700 clamp(30px,3.4vw,38px)/1 Archivo,sans-serif",
    fontVariationSettings: "'wdth' 108",
    color: "#FFFFFF",
    fontVariant: "tabular-nums",
  } as CSSProperties,
  kesSuffix: { font: "400 13px/1.3 'Instrument Sans',sans-serif", color: "#A7B0BE" },
  darkBody: { margin: "0 0 16px", font: "400 13px/1.6 'Instrument Sans',sans-serif", color: "#A7B0BE", textWrap: "pretty" } as CSSProperties,
  darkChipRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  darkChip: {
    padding: "5px 10px",
    border: "1px solid #2A3346",
    borderRadius: 999,
    font: "500 11px/1.2 'IBM Plex Mono',monospace",
    letterSpacing: ".05em",
    color: "#C6CEDA",
  },

  // --- card with a divided header row ("Have these ready") ----------------
  panel: { background: "#FFFFFF", border: "1px solid #E4E7EC", borderRadius: 12, overflow: "hidden" },
  panelHead: {
    padding: "15px 18px",
    borderBottom: "1px solid #F1F3F6",
    font: "600 15px/1.2 Archivo,sans-serif",
    color: "#0B0F1A",
  },
  panelBody: { padding: "16px 18px", display: "grid", gap: 16 },
  panelGroupLabel: {
    font: "500 11px/1 'IBM Plex Mono',monospace",
    letterSpacing: ".09em",
    color: "#838C9B",
    marginBottom: 9,
  },
  panelNote: {
    paddingTop: 14,
    borderTop: "1px solid #F1F3F6",
    font: "400 13px/1.55 'Instrument Sans',sans-serif",
    color: "#5A6373",
    textWrap: "pretty",
  } as CSSProperties,

  // --- generic card -----------------------------------------------------
  card: {
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 12,
    padding: "clamp(16px,2.4vw,20px)",
    marginBottom: 14,
  },
  cardTitle: { font: "600 16px/1.3 'Instrument Sans',sans-serif", color: "#0B0F1A", marginBottom: 4 },
  cardHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 16 },

  // --- form fields --------------------------------------------------------
  formGrid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 },
  formGrid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 18 },
  label: { display: "block", font: "600 13px/1.3 'Instrument Sans',sans-serif", color: "#1A1F2B", marginBottom: 7 },
  required: { color: "#D81E32" },
  input: {
    width: "100%",
    height: 44,
    padding: "0 13px",
    background: "#FFFFFF",
    border: "1px solid #CDD2DA",
    borderRadius: 8,
    font: "400 14px/1 'Instrument Sans',sans-serif",
    color: "#0B0F1A",
  },
  inputDisabled: { background: "#F1F3F6", color: "#838C9B", cursor: "not-allowed" },
  phonePrefix: {
    width: 64,
    height: 44,
    flex: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#F1F3F6",
    border: "1px solid #CDD2DA",
    borderRadius: 8,
    font: "500 14px/1 'IBM Plex Mono',monospace",
    color: "#5A6373",
  },
  // --- combobox (make / model suggestions) --------------------------------
  comboList: {
    position: "absolute",
    zIndex: 20,
    top: "calc(100% + 4px)",
    left: 0,
    right: 0,
    margin: 0,
    padding: 4,
    listStyle: "none",
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 8,
    boxShadow: "0 2px 4px -1px rgba(11,15,26,.06), 0 6px 14px -4px rgba(11,15,26,.09)",
    maxHeight: 260,
    overflowY: "auto",
  } as CSSProperties,
  comboOption: {
    padding: "8px 10px",
    borderRadius: 6,
    font: "400 14px/1.3 'Instrument Sans',sans-serif",
    color: "#1A1F2B",
    cursor: "pointer",
  },
  comboOptionActive: { background: "#EDEFFC", color: "#0F23A8" },
  comboEmpty: {
    padding: "8px 10px",
    font: "400 12px/1.4 'Instrument Sans',sans-serif",
    color: "#838C9B",
  },

  checkChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    height: 34,
    padding: "0 12px",
    borderRadius: 999,
    border: "1px solid #CDD2DA",
    background: "#FFFFFF",
    color: "#5A6373",
    font: "600 12px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
    marginBottom: 16,
  },
  checkChipOn: { border: "1px solid #A8DEC7", background: "#DDF3E9", color: "#076945" },
  checkChipBox: {
    width: 16,
    height: 16,
    borderRadius: 999,
    color: "#FFFFFF",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
  },
  select: {
    width: "100%",
    height: 44,
    padding: "0 13px",
    background: "#FFFFFF",
    border: "1px solid #CDD2DA",
    borderRadius: 8,
    font: "400 14px/1 'Instrument Sans',sans-serif",
    color: "#1A1F2B",
    appearance: "auto" as const,
  },
  kesPrefixTag: {
    height: 44,
    padding: "0 13px",
    display: "inline-flex",
    alignItems: "center",
    background: "#F1F3F6",
    border: "1px solid #CDD2DA",
    borderRight: "none",
    borderRadius: "8px 0 0 8px",
    font: "500 13px/1 'IBM Plex Mono',monospace",
    color: "#333B4A",
    flex: "none",
  },
  helper: { font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#9AA2B0", marginTop: 6 },
  fieldError: { font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#D81E32", marginTop: 6 },

  // --- selectable option cards (individual / company, mpesa / bank) -------
  optionGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  optionCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: 16,
    borderRadius: 10,
    border: "1.5px solid #CDD2DA",
    background: "#FFFFFF",
    cursor: "pointer",
    textAlign: "left",
  } as CSSProperties,
  optionCardActive: { border: "1.5px solid #0F23A8", background: "#EDEFFC" },
  optionCardDisabled: { opacity: 0.5, cursor: "not-allowed" },
  /** Wrapper for the radio glyph - `display:flex` so the SVG has no
   *  inline-baseline gap and sits optically centred against the label. */
  radioMark: { display: "flex", alignItems: "center", flex: "none", marginTop: 1 },
  optionTitle: { font: "600 14px/1.3 'Instrument Sans',sans-serif", color: "#0B0F1A" },
  optionBody: { font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#838C9B", marginTop: 2 },

  // --- badge-style section eyebrow (Owner details / Payout account) -------
  sectionBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    borderRadius: 999,
    background: "#0F23A8",
    color: "#FFFFFF",
    flex: "none",
  },
  /** Same badge, squared off - used for the company/organisation mark. */
  sectionBadgeSquare: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    borderRadius: 10,
    background: "#0F23A8",
    color: "#FFFFFF",
    flex: "none",
  },

  // --- section panel: divided header band over a white body --------------
  section: {
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 14,
  },
  sectionHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "14px 18px",
    background: "#F8F9FB",
    borderBottom: "1px solid #E4E7EC",
  },
  sectionHeadLeft: { display: "flex", alignItems: "center", gap: 12, minWidth: 0 },
  sectionTitle: { font: "600 15px/1.3 'Instrument Sans',sans-serif", color: "#0B0F1A" },
  sectionSub: { font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#838C9B", marginTop: 2 },
  sectionAside: {
    font: "500 10px/1 'IBM Plex Mono',monospace",
    letterSpacing: ".09em",
    color: "#A7AEBB",
    flex: "0 0 auto",
  },
  sectionBody: { padding: 18 },
  /** Quiet explanatory box at the foot of a section. */
  noteBox: {
    padding: "12px 14px",
    background: "#F8F9FB",
    border: "1px solid #E4E7EC",
    borderRadius: 8,
    font: "400 12px/1.5 'Instrument Sans',sans-serif",
    color: "#5A6373",
    textWrap: "pretty",
  } as CSSProperties,

  // --- plate badge --------------------------------------------------------
  plateBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "5px 11px",
    border: "1.5px solid #0B0F1A",
    borderRadius: 4,
    font: "600 15px/1.2 'IBM Plex Mono',monospace",
    letterSpacing: ".05em",
    color: "#0B0F1A",
    flex: "0 0 auto",
  },

  // --- toggle switch --------------------------------------------------------
  toggleTrack: {
    width: 44,
    height: 24,
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    padding: 3,
    border: "none",
    cursor: "pointer",
    transition: "background 120ms cubic-bezier(.2,.8,.25,1)",
  },
  toggleTrackOn: { background: "#0F23A8", justifyContent: "flex-end" },
  toggleTrackOff: { background: "#CDD2DA", justifyContent: "flex-start" },
  toggleThumb: { width: 18, height: 18, borderRadius: 999, background: "#FFFFFF" },
  toggleOnLabel: { font: "600 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".08em", color: "#0F23A8" },
  toggleOffLabel: { font: "600 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".08em", color: "#9AA2B0" },

  // --- demand pricing chip row ----------------------------------------------
  demandRow: { padding: "16px 0", borderTop: "1px solid #E4E7EC" },
  demandLabel: { font: "600 14px/1.3 'Instrument Sans',sans-serif", color: "#1A1F2B" },
  demandHint: { font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#838C9B", marginTop: 2, marginBottom: 12 },
  chipGroup: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 8 },
  chip: {
    height: 36,
    borderRadius: 8,
    border: "1px solid #CDD2DA",
    background: "#FFFFFF",
    font: "600 13px/1 'Instrument Sans',sans-serif",
    color: "#333B4A",
    cursor: "pointer",
  },
  chipActive: { background: "#0F23A8", color: "#FFFFFF", border: "1px solid #0F23A8" },

  // --- vehicle summary sidebar -------------------------------------------
  sideCard: { background: "#FFFFFF", border: "1px solid #E4E7EC", borderRadius: 12, padding: 20 },
  sideRow: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 0", borderBottom: "1px solid #F1F3F6" },
  sideRowHighlight: { background: "#EDEFFC", margin: "0 -20px", padding: "16px 20px", borderRadius: 8, borderBottom: "none" },
  sideRowLabel: { font: "500 13px/1.3 'Instrument Sans',sans-serif", color: "#5A6373" },
  sideRowSub: { font: "600 11px/1 'Instrument Sans',sans-serif", marginTop: 2 },
  sideRowValue: { font: "600 14px/1 'IBM Plex Mono',monospace", color: "#0B0F1A", fontFeatureSettings: "'tnum'" },

  // --- photos --------------------------------------------------------------
  photoGrid: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12, marginBottom: 10 },
  photoTileEmpty: {
    aspectRatio: "4 / 3",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    border: "1.5px dashed #CDD2DA",
    borderRadius: 10,
    background: "#FAFBFC",
    cursor: "pointer",
  } as CSSProperties,
  photoTileEmptyActive: { border: "1.5px dashed #0F23A8", background: "#EDEFFC" } as CSSProperties,
  photoTileAddLabel: { font: "600 11px/1 'IBM Plex Mono',monospace", letterSpacing: ".06em", color: "#0F23A8" },
  photoTileCaption: { font: "400 11px/1.3 'Instrument Sans',sans-serif", color: "#9AA2B0", textAlign: "center", padding: "0 6px" },
  photoTileHint: { font: "400 10px/1.3 'Instrument Sans',sans-serif", color: "#CDD2DA", textAlign: "center" },
  photoTileFilled: { display: "flex", flexDirection: "column", border: "1px solid #E4E7EC", borderRadius: 10, overflow: "hidden" },
  /** Real preview once a file's been picked this session. */
  photoThumbImage: { aspectRatio: "4 / 3", width: "100%", objectFit: "cover", display: "block" } as CSSProperties,
  /** Filled tile after a reload, when the file itself is gone but its
   *  metadata survived - no bytes to preview, so a plain icon stands in. */
  photoThumbFallback: {
    aspectRatio: "4 / 3",
    background: "#F8F9FB",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  } as CSSProperties,
  photoFileRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "8px 10px" },
  photoFileName: { font: "400 12px/1.3 'Instrument Sans',sans-serif", color: "#5A6373", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } as CSSProperties,
  photoRemove: {
    width: 22,
    height: 22,
    borderRadius: 6,
    border: "1px solid #F7BDC5",
    background: "#FDE7EA",
    color: "#D81E32",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flex: "none",
    font: "600 12px/1 sans-serif",
  },

  // --- pending/complete pills ---------------------------------------------
  statusPillBase: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 26,
    padding: "0 11px",
    borderRadius: 999,
    font: "600 11px/1 'Instrument Sans',sans-serif",
    border: "1px solid transparent",
  },
  statusDot: { width: 6, height: 6, borderRadius: 999, flex: "none" },

  // --- document rows ------------------------------------------------------
  docRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    padding: "16px 0",
    borderTop: "1px solid #F1F3F6",
    borderRadius: 8,
    transition: "background 120ms cubic-bezier(.2,.8,.25,1)",
  } as CSSProperties,
  docRowDrag: { background: "#EDEFFC" },

  // --- expiry field, inside an attached document row ----------------------
  expiryRow: {
    marginTop: 14,
    paddingTop: 14,
    borderTop: "1px solid #F1F3F6",
    display: "flex",
    alignItems: "flex-end",
    gap: 14,
    flexWrap: "wrap",
  } as CSSProperties,
  expiryLabel: {
    display: "block",
    font: "600 12px/1.3 'Instrument Sans',sans-serif",
    color: "#1A1F2B",
    marginBottom: 6,
  },
  expiryInput: {
    width: "auto",
    height: 40,
    padding: "0 12px",
    border: "1px solid #CDD2DA",
    borderRadius: 4,
    background: "#FFFFFF",
    font: "500 13px/1 'IBM Plex Mono',monospace",
    color: "#0B0F1A",
    outline: "none",
  },
  expiryHelper: {
    font: "400 12px/1.5 'Instrument Sans',sans-serif",
    color: "#838C9B",
    paddingBottom: 12,
    flex: "1 1 0%",
    minWidth: 180,
  } as CSSProperties,
  docIconEmpty: {
    width: 36,
    height: 36,
    borderRadius: 999,
    border: "1.5px dashed #CDD2DA",
    color: "#9AA2B0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "none",
    font: "600 16px/1 sans-serif",
  },
  docIconDone: {
    width: 36,
    height: 36,
    borderRadius: 999,
    background: "#0B8A5B",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "none",
    font: "700 14px/1 sans-serif",
  },
  docTitle: { font: "600 14px/1.3 'Instrument Sans',sans-serif", color: "#0B0F1A" },
  docBody: { font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#838C9B", marginTop: 2 },
  docFileRow: { display: "flex", alignItems: "center", gap: 8, marginTop: 2 },
  docFile: {
    font: "400 12px/1.4 'IBM Plex Mono',monospace",
    color: "#5A6373",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } as CSSProperties,
  docRemoveSmall: {
    width: 18,
    height: 18,
    borderRadius: 999,
    border: "1px solid #F7BDC5",
    background: "#FDE7EA",
    color: "#D81E32",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    cursor: "pointer",
    flex: "none",
  },

  // --- buttons -------------------------------------------------------------
  primaryBtn: {
    height: 48,
    padding: "0 24px",
    background: "#0F23A8",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 8,
    font: "600 15px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
    transition: "background 120ms cubic-bezier(.2,.8,.25,1)",
  },
  primaryBtnHover: { background: "#0B1B85" },
  primaryBtnSmall: {
    height: 36,
    padding: "0 16px",
    background: "#0F23A8",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 8,
    font: "600 13px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
  },
  secondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 9,
    height: 48,
    padding: "0 20px",
    background: "#FFFFFF",
    color: "#1A1F2B",
    border: "1px solid #CDD2DA",
    borderRadius: 8,
    font: "600 15px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
    transition: "background 120ms cubic-bezier(.2,.8,.25,1), border-color 120ms cubic-bezier(.2,.8,.25,1)",
  },
  secondaryBtnHover: { background: "#F8F9FB", border: "1px solid #A7AEBB" },
  secondaryBtnSmall: {
    height: 36,
    padding: "0 16px",
    background: "#FFFFFF",
    color: "#1A1F2B",
    border: "1px solid #CDD2DA",
    borderRadius: 8,
    font: "600 13px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
  },
  ghostLinkBtn: {
    background: "none",
    border: "none",
    padding: 0,
    font: "600 13px/1 'Instrument Sans',sans-serif",
    color: "#0F23A8",
    cursor: "pointer",
  },
  dashedAddRow: {
    width: "100%",
    padding: 20,
    border: "1px dashed #CDD2DA",
    borderRadius: 12,
    background: "#FFFFFF",
    color: "#0F23A8",
    font: "600 14px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
    marginBottom: 16,
  },

  // --- errors --------------------------------------------------------------
  errorBanner: {
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "13px 15px",
    background: "#FDE7EA",
    border: "1px solid #F7BDC5",
    borderRadius: 8,
    marginTop: 12,
  },
  errorDot: { width: 8, height: 8, borderRadius: 999, background: "#D81E32", flex: "none" },
  errorText: { font: "600 13px/1.45 'Instrument Sans',sans-serif", color: "#A50E22" },

  // --- footer ---------------------------------------------------------------
  footer: {
    background: "#0B0F1A",
    color: "#8C97A8",
    padding: "22px clamp(18px,4vw,40px)",
  },
  footerInner: {
    maxWidth: 1120,
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
  },
  footerLeft: { display: "flex", alignItems: "center", gap: 12 },
  footerText: { font: "500 11px/1.6 'IBM Plex Mono',monospace", letterSpacing: ".08em" },
  footerRight: { font: "500 11px/1.6 'IBM Plex Mono',monospace", letterSpacing: ".08em", color: "#5F6B7C" },

  // --- fleet list rows -------------------------------------------------------
  fleetList: { display: "grid", gap: 12, marginBottom: 16 },
  fleetRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "16px 18px",
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 12,
    flexWrap: "wrap",
  },
  fleetName: { font: "600 15px/1.25 Archivo,sans-serif", color: "#0B0F1A" },
  fleetSub: { font: "400 12px/1.4 'Instrument Sans',sans-serif", color: "#838C9B", marginTop: 3 },
  fleetRate: { font: "600 15px/1.2 Archivo,sans-serif", color: "#0B0F1A", fontVariant: "tabular-nums" } as CSSProperties,
  fleetRatePrefix: { font: "500 11px/1 'Instrument Sans',sans-serif", color: "#838C9B", letterSpacing: ".04em", marginRight: 4 },
  fleetRateSuffix: { font: "400 12px/1 'Instrument Sans',sans-serif", color: "#838C9B" },
  fleetActions: { display: "flex", gap: 8, flexWrap: "wrap", flex: "0 0 auto" },
  fleetEditBtn: {
    height: 36,
    padding: "0 14px",
    background: "#FFFFFF",
    color: "#1A1F2B",
    border: "1px solid #CDD2DA",
    borderRadius: 8,
    font: "600 13px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
  },
  fleetRemoveBtn: {
    height: 36,
    padding: "0 12px",
    background: "#FFFFFF",
    color: "#A50E22",
    border: "1px solid #F7BDC5",
    borderRadius: 8,
    font: "600 13px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
  },

  // --- review screen ----------------------------------------------------------
  reviewGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 },
  // --- review-step summary cards: header band + body, not the flat O.card --
  reviewCard: {
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
  } as CSSProperties,
  reviewCardHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "14px 18px",
    borderBottom: "1px solid #F1F3F6",
    flexWrap: "wrap",
  } as CSSProperties,
  reviewCardBody: { padding: "16px 18px", display: "grid", gap: 11 },
  reviewEditBtn: {
    height: 30,
    padding: "0 12px",
    background: "#FFFFFF",
    color: "#0F23A8",
    border: "1px solid #CDD2DA",
    borderRadius: 4,
    font: "600 12px/1 'Instrument Sans',sans-serif",
    cursor: "pointer",
    transition: "background 120ms cubic-bezier(.2,.8,.25,1), border-color 120ms cubic-bezier(.2,.8,.25,1)",
  },
  reviewEditBtnHover: { background: "#F8F9FB", border: "1px solid #A7AEBB" },
  // --- vehicle photo thumbnails, review step -----------------------------
  reviewPhotoRow: { display: "flex", gap: 6, marginTop: 8 },
  reviewPhotoThumb: {
    width: 40,
    height: 40,
    borderRadius: 6,
    objectFit: "cover",
    border: "1px solid #E4E7EC",
    flex: "0 0 auto",
  } as CSSProperties,
  reviewPhotoFallback: {
    width: 40,
    height: 40,
    borderRadius: 6,
    border: "1px solid #E4E7EC",
    background: "#F8F9FB",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
  },

  reviewRequiredPill: {
    padding: "4px 10px",
    background: "#FFF3DB",
    border: "1px solid #F5D9A3",
    borderRadius: 999,
    font: "500 11px/1.2 'IBM Plex Mono',monospace",
    letterSpacing: ".08em",
    color: "#8A5200",
    flex: "0 0 auto",
  },
  reviewRow: { display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" } as CSSProperties,
  reviewLabel: { font: "400 13px/1.4 'Instrument Sans',sans-serif", color: "#838C9B" },
  reviewValue: { font: "500 13px/1.4 'IBM Plex Mono',monospace", color: "#0B0F1A", textAlign: "right" } as CSSProperties,
  // The payout row sits below a divider and reads bolder - it's the one
  // number on this card a merchant is most likely to double-check.
  reviewRowPayout: { borderTop: "1px solid #F1F3F6", paddingTop: 11 },
  reviewLabelPayout: { font: "600 13px/1.4 'Instrument Sans',sans-serif", color: "#0F23A8" },
  reviewValuePayout: { font: "600 13px/1.4 'IBM Plex Mono',monospace", color: "#0B0F1A", textAlign: "right" } as CSSProperties,
  termsBox: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "13px 14px",
    background: "#F8F9FB",
    border: "1px solid #A7AEBB",
    borderRadius: 8,
    // Buttons default to centered text in Chrome's UA stylesheet; without
    // this the wrapped second line of termsText drifts to the middle.
    textAlign: "left",
  } as CSSProperties,
  termsBoxActive: { border: "1px solid #0B8A5B", background: "#DDF3E9" },
  termsBoxError: { border: "1px solid #D81E32" },
  termsCheck: {
    width: 24,
    height: 24,
    borderRadius: 5,
    border: "1.5px solid #A7AEBB",
    flex: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#FFFFFF",
    font: "700 12px/22px 'Instrument Sans',sans-serif",
    textAlign: "center",
  } as CSSProperties,
  termsCheckActive: { background: "#0B8A5B", border: "1.5px solid #0B8A5B" },
  termsText: { font: "500 13px/1.55 'Instrument Sans',sans-serif", color: "#1A1F2B", textWrap: "pretty" } as CSSProperties,

  // --- done screen --------------------------------------------------------
  doneWrap: { textAlign: "center", maxWidth: 640, margin: "0 auto" } as CSSProperties,
  doneCheck: {
    width: 56,
    height: 56,
    borderRadius: 999,
    background: "#DDF3E9",
    color: "#0B8A5B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 20px",
    font: "700 24px/1 sans-serif",
  },
  doneHeading: {
    margin: "0 0 10px",
    font: "700 clamp(26px,3.6vw,38px)/1.05 Archivo,sans-serif",
    fontVariationSettings: "'wdth' 110",
    letterSpacing: "-.026em",
    color: "#0B0F1A",
  } as CSSProperties,
  doneLede: { margin: "0 0 28px", font: "400 15px/1.6 'Instrument Sans',sans-serif", color: "#5A6373" },
  // --- submitted screen: one compact row per vehicle ----------------------
  doneVehicleRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "13px 18px",
    flexWrap: "wrap",
    textAlign: "left",
  } as CSSProperties,
  doneVehicleThumb: {
    width: 64,
    height: 48,
    borderRadius: 6,
    objectFit: "cover",
    border: "1px solid #E4E7EC",
    flex: "0 0 auto",
    display: "block",
  } as CSSProperties,
  doneVehicleThumbFallback: {
    width: 64,
    height: 48,
    borderRadius: 6,
    border: "1px solid #E4E7EC",
    background: "#F8F9FB",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
  },

  nextStepsCard: { textAlign: "left", background: "#FFFFFF", border: "1px solid #E4E7EC", borderRadius: 12, padding: 20, marginTop: 20 },
  nextStepEyebrow: { font: "500 10px/1 'IBM Plex Mono',monospace", letterSpacing: ".1em", color: "#9AA2B0", marginBottom: 14 },
  nextStepRow: { display: "flex", gap: 12, marginBottom: 16 },
  nextStepDot: { width: 8, height: 8, borderRadius: 999, marginTop: 6, flex: "none" },
  nextStepTitle: { font: "600 14px/1.3 'Instrument Sans',sans-serif", color: "#0B0F1A" },
  nextStepBody: { font: "400 12px/1.5 'Instrument Sans',sans-serif", color: "#838C9B", marginTop: 2 },
} satisfies Record<string, CSSProperties>;
